SET AUTOBATCHSEQU=C:\Users\Administrator\AppData\Roaming\Adobe\Acrobat\11.0\Sequences\Pdf To Png.sequ
SET AUTOBATCHFINAL=0
SET AUTOBATCHDEST=
SET AUTOBATCHALTPATH=%1
SET AUTOBATCHALTOUTPUTPATH=%2
SET AUTOBATCHNOPROGRESS=yes
SET AUTOBATCHFILEEXT=
SET AUTOBATCHNOSUBFOLDERS=no
"C:\Program Files (x86)\Adobe\Acrobat 11.0\Acrobat\Acrobat.exe" /n /h